### ISSUE TITLE
Policy for building new binaries here

### ISSUE THREAD

**Issue by yeesian** [JuliaGeo/PROJBuilder#1]
Should we be matching them to every major-minor release? Or just whenever there's a request?

**Comment by visr** [comment]
Since it is not directly linked to Proj4.jl, but a fixed link to a certain build/release is used there, we are free to build different versions.

It only builds if we tag a release, and I've used the same naming setup as I saw staticfloat use, v4.9.3-0, so the PROJ version followed by a build number.

But yeah, to answer your question, it would be nice to try to keep relatively up to date, but I'm not sure I can promise anything. So people can always make a request/PR if we are lagging. I wasn't even aware that PROJ 5 was out when I started this... Which is probably another issue to discuss in Proj4.jl. I stuck with PROJ 4 for now not to change too much at the same time, and since GDAL cannot use it (GDAL trunk can).

**Comment by yeesian** [comment]
I'm wondering what is our recourse if we skip one of the minor patches, and later get a request for it when we've "moved on" in this repository. But I guess the order in which we tag and release the binaries here doesn't have to match semver conventions?

**Comment by visr** [comment]
No indeed the order doesn't matter here. As long as we bump the build number when rebuilding the same version it should be fine.

**Comment by yeesian** [comment]
Okay, thanks for the clarification
